version: "3"
services:
  doccano:
#    image: chakkiworks/doccano
    build:
       context: .
       dockerfile: Dockerfile
    ports:
      - '50011:80'
    volumes:
      - doccano:/doccano

volumes:
  doccano: